# Generated by Django 2.0.5 on 2018-05-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog_posts',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog_posts',
            name='tag',
        ),
        migrations.AddField(
            model_name='blog_posts',
            name='text',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_posts',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
